// <auto-generated />
namespace BarSanAntonioAPP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class campos_agregados_tabla_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(campos_agregados_tabla_user));
        
        string IMigrationMetadata.Id
        {
            get { return "201910032029275_campos_agregados_tabla_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
