// <auto-generated />
namespace BarSanAntonioAPP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class agregandotablasdelproyectoviejo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agregandotablasdelproyectoviejo));
        
        string IMigrationMetadata.Id
        {
            get { return "201910031958280_agregando tablas del proyecto viejo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
