// <auto-generated />
namespace Mibar7._9.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class boraradtablausuario : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(boraradtablausuario));
        
        string IMigrationMetadata.Id
        {
            get { return "201910021641411_borarad tabla usuario"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
